### ISSUE TITLE
Update for the DEV-13956 SparkFun Weather Shield

### ISSUE THREAD

**Issue by Soren234** [rwaldron/j5-sparkfun-weather-shield#4]
Hi there,
Thanks for this lib.

Is it possible for you to update this library for the DEV-13956 SparkFun Weather Shield? 
https://www.sparkfun.com/products/13956

This board uses Si7021 humidity/temperature sensor, MPL3115A2 barometric pressure sensor and the  ALS-PT19 light sensor. These sensors seems not to be supported in this release.

**Comment by rwaldron** [comment]
I'll try to address this on Monday

**Comment by rwaldron** [comment]
~~Funny story... I just went to purchase one of these and discovered that I already bought one a few years ago, but never implemented support for it. I will work on this today~~

That was the older model 🤦‍♂

**Comment by rwaldron** [comment]
@Soren234 can you test out the latest code on master? 

1. `npm install rwaldron/j5-sparkfun-weather-shield`
2. Look at the updated examples in eg/ (or in the README). Hopefully the only change you need to make to your code is `variant: "ARDUINO"` -> `variant: "DEV-13956"`

**Comment by Soren234** [comment]
@rwaldron Thank you for your update. 😄 

This is the result i am getting from "j5-sparkfun-weather-shield": "github:rwaldron/j5-sparkfun-weather-shield":

```
celsius: 23°C
fahrenheit: 74°F
kelvin: 296.7°K
pressure: 100.3471 kPa
feet: 125'
meters: 38.1
relativeHumidity: 38.22 RH
lightLevel: 0.58%

celsius: 23°C
fahrenheit: 74°F
kelvin: 296.7°K
pressure: 100.3471 kPa
feet: 125'
meters: 38.1
relativeHumidity: 38.2 RH
lightLevel: 0.57%
```


This is my code within board.on("ready" ..):

```
const weather = new Weather({
    variant: "DEV-13956",
    period: 1000,
    elevation: 38,
  });
  weather.on("data", () => {
    const {
      celsius,
      fahrenheit,
      kelvin,
      pressure,
      feet,
      meters,
      relativeHumidity,
      lightLevel
    } = weather;

    console.log("celsius: %d°C", celsius);
    console.log("fahrenheit: %d°F", fahrenheit);
    console.log("kelvin: %d°K", kelvin);
    console.log("pressure: %d kPa", pressure);
    console.log("feet: %d'", feet);
    console.log("meters: %d", meters);
    console.log("relativeHumidity: %d RH", relativeHumidity);
    console.log("lightLevel: %d%", lightLevel);
  });
```

Seems working well. 👍

**Comment by Soren234** [comment]
When reading the documentation on the MPL3115A2 sensor, it seems that it has a temperature function? So should it be possible to monitor the temperature with both the MPL3115A2 and the Si7021 sensors i would guess.  What do you think?
At 6.3 Temperature Function:
https://cdn.sparkfun.com/datasheets/Sensors/Pressure/MPL3115A2.pdf

**Comment by rwaldron** [comment]
@Soren234 

> So should it be possible to monitor the temperature with both the MPL3115A2 and the Si7021 sensors i would guess. 

Indeed! And it does! 😄 


https://github.com/rwaldron/j5-sparkfun-weather-shield/blob/75fcb5d6b61797eaa7a240ca43d423ca207f5326/index.js#L121-L147

I can expose the individual sensor instances as well.

**Comment by rwaldron** [comment]
You can now also access individual sensors!

```js
const weather = new Weather({
  variant: "DEV-13956"
});
weather.sensors.MPL3115A2;
weather.sensors.SI7021;
weather.sensors.ALSPT19;
```


Released: https://www.npmjs.com/package/j5-sparkfun-weather-shield/v/2.0.0

**Comment by rwaldron** [comment]
Closing this now—let me know if there are any issues :)
